export const typeList: string[] = [  
    'Liqueur',
    'Spice',
    'Fruit Juice',
    'Spirit',
    'Beverage',
    'Vodka',
    'Nuts',
    'Syrup',
    'Brandy',
    'Rum',
    'Fruit',
    'Wine',
    'Beer',
    'Others',
    'Soft Drink',
    'Whiskey',
    'Bitter',
    'Vegetable',
    'Sambuca',
    'Cream',
    'Sherry',
    'Whisky',
    'Herb',
    'Herb Liqueur',
    'Apple Brandy',
    'Schnapps',
    'Cider',
    'Coloring',
    'Aperitif',
    'Nut',
    'Coffee',
    'Juice',
    'Stout',
    'Liquor',
    'Fortified Wine',
    'Tequila',
    'Mezcal',
    'Rice wine',
    'liqueur',
    'Fortified wine',
    'Vermouth',
    'aperitif',
    'Cordial',
    'Water',
    'Garnish',
    'Confectionery',
    'Mixer',
    'Flower',
    'Gin',
    'Liquer'
];
    
export  const alcoholList: string[] = [
        'No',
        'Yes'
    ];